// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * @param {string} path
 * @returns {$CancellablePromise<boolean>}
 */
export function DirExists(path) {
    return $Call.ByID(1033750750, path);
}

/**
 * @param {string} path
 * @returns {$CancellablePromise<boolean>}
 */
export function FileExists(path) {
    return $Call.ByID(2423613713, path);
}

/**
 * @param {string} archivePath
 * @param {string} fileInside
 * @returns {$CancellablePromise<[boolean, string]>}
 */
export function FileExistsInZip(archivePath, fileInside) {
    return $Call.ByID(2090288553, archivePath, fileInside);
}

/**
 * @param {string} path
 * @returns {$CancellablePromise<string>}
 */
export function GetDir(path) {
    return $Call.ByID(4129528336, path);
}

/**
 * @returns {$CancellablePromise<string>}
 */
export function GetLauncherDir() {
    return $Call.ByID(1772893036);
}

/**
 * @param {string[]} gameIDs
 * @param {string} region
 * @returns {$CancellablePromise<$models.SophonVersion[]>}
 */
export function GetSophonVersions(gameIDs, region) {
    return $Call.ByID(737472939, gameIDs, region).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * @param {string[]} paths
 * @returns {$CancellablePromise<string>}
 */
export function Join(...paths) {
    return $Call.ByID(3626794327, paths);
}

/**
 * @param {string} path
 * @returns {$CancellablePromise<[boolean, string]>}
 */
export function OpenFolder(path) {
    return $Call.ByID(3607094079, path);
}

/**
 * @param {string} filter
 * @returns {$CancellablePromise<string>}
 */
export function PickFile(filter) {
    return $Call.ByID(2058553420, filter);
}

/**
 * @returns {$CancellablePromise<string>}
 */
export function PickFolder() {
    return $Call.ByID(1227184466);
}

/**
 * @param {string} path
 * @returns {$CancellablePromise<void>}
 */
export function RemoveFile(path) {
    return $Call.ByID(2233966485, path);
}

/**
 * @param {string} gameID
 * @param {string} pkg
 * @param {string} version
 * @param {string} output
 * @param {string} region
 * @param {string} branch
 * @param {string} launcherID
 * @returns {$CancellablePromise<boolean>}
 */
export function RunDownloader(gameID, pkg, version, output, region, branch, launcherID) {
    return $Call.ByID(2108586039, gameID, pkg, version, output, region, branch, launcherID);
}

/**
 * @param {string} path
 * @returns {$CancellablePromise<[boolean, string]>}
 */
export function StartApp(path) {
    return $Call.ByID(849726548, path);
}

/**
 * @param {string} path
 * @returns {$CancellablePromise<[boolean, string]>}
 */
export function StartWithConsole(path) {
    return $Call.ByID(333959942, path);
}

// Private type creation functions
const $$createType0 = $models.SophonVersion.createFrom;
const $$createType1 = $Create.Array($$createType0);
