// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

export class SophonVersion {
    /**
     * Creates a new SophonVersion instance.
     * @param {Partial<SophonVersion>} [$$source = {}] - The source object to create the SophonVersion.
     */
    constructor($$source = {}) {
        if (!("gameId" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["gameId"] = "";
        }
        if (!("launcherId" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["launcherId"] = "";
        }
        if (!("region" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["region"] = "";
        }
        if (!("version" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["version"] = "";
        }
        if (!("branch" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["branch"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SophonVersion instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {SophonVersion}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new SophonVersion(/** @type {Partial<SophonVersion>} */($$parsedSource));
    }
}
