// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

/**
 * @param {string} path
 * @returns {$CancellablePromise<boolean>}
 */
export function DirExists(path) {
    return $Call.ByID(1761493329, path);
}

/**
 * @param {string} path
 * @returns {$CancellablePromise<boolean>}
 */
export function FileExists(path) {
    return $Call.ByID(306036500, path);
}

/**
 * @param {string} archivePath
 * @param {string} fileInside
 * @returns {$CancellablePromise<[boolean, string]>}
 */
export function FileExistsInZip(archivePath, fileInside) {
    return $Call.ByID(3837786058, archivePath, fileInside);
}

/**
 * @param {string} path
 * @returns {$CancellablePromise<string>}
 */
export function GetDir(path) {
    return $Call.ByID(1591294533, path);
}

/**
 * @returns {$CancellablePromise<[string, string]>}
 */
export function GetSavedGameSelection() {
    return $Call.ByID(3714295579);
}

/**
 * @param {string[]} paths
 * @returns {$CancellablePromise<string>}
 */
export function Join(...paths) {
    return $Call.ByID(1157871918, paths);
}

/**
 * @param {string} path
 * @returns {$CancellablePromise<[boolean, string]>}
 */
export function OpenFolder(path) {
    return $Call.ByID(2377465778, path);
}

/**
 * @param {string} filter
 * @returns {$CancellablePromise<string>}
 */
export function PickFile(filter) {
    return $Call.ByID(1788952397, filter);
}

/**
 * @returns {$CancellablePromise<string>}
 */
export function PickFolder() {
    return $Call.ByID(2627397847);
}

/**
 * @param {string} path
 * @returns {$CancellablePromise<void>}
 */
export function RemoveFile(path) {
    return $Call.ByID(665541824, path);
}

/**
 * @param {string} gamePath
 * @param {string} gameDir
 * @returns {$CancellablePromise<void>}
 */
export function SaveGameSelection(gamePath, gameDir) {
    return $Call.ByID(1396931989, gamePath, gameDir);
}

/**
 * @param {string} path
 * @returns {$CancellablePromise<[boolean, string]>}
 */
export function StartApp(path) {
    return $Call.ByID(4046339337, path);
}

/**
 * @param {string} path
 * @returns {$CancellablePromise<[boolean, string]>}
 */
export function StartWithConsole(path) {
    return $Call.ByID(1563952671, path);
}
