// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

/**
 * @returns {$CancellablePromise<[boolean, string]>}
 */
export function CloseApp() {
    return $Call.ByID(3089952202);
}

/**
 * @param {number} timeout
 * @returns {$CancellablePromise<[boolean, string]>}
 */
export function CloseAppAfterTimeout(timeout) {
    return $Call.ByID(3461485987, timeout);
}

/**
 * @returns {$CancellablePromise<[boolean, string]>}
 */
export function GetCurrentLauncherVersion() {
    return $Call.ByID(3475795024);
}

/**
 * @returns {$CancellablePromise<[boolean, string]>}
 */
export function HideApp() {
    return $Call.ByID(2412730616);
}

/**
 * @returns {$CancellablePromise<[boolean, string]>}
 */
export function MaximizeApp() {
    return $Call.ByID(2899219270);
}

/**
 * @returns {$CancellablePromise<[boolean, string]>}
 */
export function MinimizeApp() {
    return $Call.ByID(3507844888);
}

/**
 * @returns {$CancellablePromise<[boolean, string]>}
 */
export function RestoreApp() {
    return $Call.ByID(4050673740);
}

/**
 * @param {number} width
 * @param {number} height
 * @returns {$CancellablePromise<[boolean, string]>}
 */
export function SetWindowSize(width, height) {
    return $Call.ByID(3945719902, width, height);
}
