// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

/**
 * @param {string} path
 * @returns {$CancellablePromise<[boolean, string, string, string]>}
 */
export function GetLanguage(path) {
    return $Call.ByID(3437273138, path);
}

/**
 * @param {string} gameRoot
 * @param {string} packageRoot
 * @returns {$CancellablePromise<[boolean, string]>}
 */
export function InstallThaiPatch(gameRoot, packageRoot) {
    return $Call.ByID(2582310097, gameRoot, packageRoot);
}

/**
 * @param {string} path
 * @param {string} text
 * @param {string} voice
 * @returns {$CancellablePromise<[boolean, string]>}
 */
export function SetLanguage(path, text, voice) {
    return $Call.ByID(4024802238, path, text, voice);
}
