// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

/**
 * @param {string} version
 * @returns {$CancellablePromise<[boolean, string]>}
 */
export function DownloadProxyProgress(version) {
    return $Call.ByID(1089029711, version);
}

/**
 * @param {string} version
 * @returns {$CancellablePromise<[boolean, string]>}
 */
export function DownloadServerProgress(version) {
    return $Call.ByID(2046961256, version);
}

/**
 * @returns {$CancellablePromise<[boolean, string, string]>}
 */
export function GetLatestLauncherVersion() {
    return $Call.ByID(4064056837);
}

/**
 * @returns {$CancellablePromise<[boolean, string, string]>}
 */
export function GetLatestProxyVersion() {
    return $Call.ByID(4068812447);
}

/**
 * @returns {$CancellablePromise<[boolean, string, string]>}
 */
export function GetLatestServerVersion() {
    return $Call.ByID(3573241564);
}

/**
 * @returns {$CancellablePromise<void>}
 */
export function UnzipProxy() {
    return $Call.ByID(3817540834);
}

/**
 * @returns {$CancellablePromise<void>}
 */
export function UnzipServer() {
    return $Call.ByID(3898887297);
}

/**
 * @param {string} version
 * @returns {$CancellablePromise<[boolean, string]>}
 */
export function UpdateLauncherProgress(version) {
    return $Call.ByID(2046545346, version);
}
