// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

/**
 * @param {string} gamePath
 * @param {string} patchPath
 * @returns {$CancellablePromise<[boolean, string]>}
 */
export function ApplyDiffZip(gamePath, patchPath) {
    return $Call.ByID(3732594501, gamePath, patchPath);
}

/**
 * @param {string} patchPath
 * @returns {$CancellablePromise<[boolean, string, string]>}
 */
export function CheckTypeHDiff(patchPath) {
    return $Call.ByID(2080569272, patchPath);
}

/**
 * @param {string} gamePath
 * @returns {$CancellablePromise<[boolean, string]>}
 */
export function CutData(gamePath) {
    return $Call.ByID(4258209693, gamePath);
}

/**
 * @param {string} gamePath
 * @param {string} patchPath
 * @returns {$CancellablePromise<[boolean, string]>}
 */
export function DataExtract(gamePath, patchPath) {
    return $Call.ByID(2606077484, gamePath, patchPath);
}

/**
 * @param {string} gamePath
 * @returns {$CancellablePromise<[boolean, string]>}
 */
export function DeleteFiles(gamePath) {
    return $Call.ByID(3232002755, gamePath);
}

/**
 * @param {string} gamePath
 * @returns {$CancellablePromise<[boolean, string]>}
 */
export function HDiffPatchData(gamePath) {
    return $Call.ByID(1438811696, gamePath);
}

/**
 * @param {string} gamePath
 * @returns {$CancellablePromise<[boolean, string]>}
 */
export function LDiffPatchData(gamePath) {
    return $Call.ByID(2729141228, gamePath);
}

/**
 * @param {string} gamePath
 * @param {string} patchPath
 * @returns {$CancellablePromise<[boolean, string]>}
 */
export function VersionValidate(gamePath, patchPath) {
    return $Call.ByID(2399382903, gamePath, patchPath);
}
