/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as NapRouteImport } from './routes/nap'
import { Route as KlRouteImport } from './routes/kl'
import { Route as HygRouteImport } from './routes/hyg'
import { Route as HowtoRouteImport } from './routes/howto'
import { Route as HkrpgRouteImport } from './routes/hkrpg'
import { Route as Hk4eRouteImport } from './routes/hk4e'
import { Route as DiffRouteImport } from './routes/diff'
import { Route as Bh3RouteImport } from './routes/bh3'
import { Route as AbcRouteImport } from './routes/abc'
import { Route as IndexRouteImport } from './routes/index'

const NapRoute = NapRouteImport.update({
  id: '/nap',
  path: '/nap',
  getParentRoute: () => rootRouteImport,
} as any)
const KlRoute = KlRouteImport.update({
  id: '/kl',
  path: '/kl',
  getParentRoute: () => rootRouteImport,
} as any)
const HygRoute = HygRouteImport.update({
  id: '/hyg',
  path: '/hyg',
  getParentRoute: () => rootRouteImport,
} as any)
const HowtoRoute = HowtoRouteImport.update({
  id: '/howto',
  path: '/howto',
  getParentRoute: () => rootRouteImport,
} as any)
const HkrpgRoute = HkrpgRouteImport.update({
  id: '/hkrpg',
  path: '/hkrpg',
  getParentRoute: () => rootRouteImport,
} as any)
const Hk4eRoute = Hk4eRouteImport.update({
  id: '/hk4e',
  path: '/hk4e',
  getParentRoute: () => rootRouteImport,
} as any)
const DiffRoute = DiffRouteImport.update({
  id: '/diff',
  path: '/diff',
  getParentRoute: () => rootRouteImport,
} as any)
const Bh3Route = Bh3RouteImport.update({
  id: '/bh3',
  path: '/bh3',
  getParentRoute: () => rootRouteImport,
} as any)
const AbcRoute = AbcRouteImport.update({
  id: '/abc',
  path: '/abc',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/abc': typeof AbcRoute
  '/bh3': typeof Bh3Route
  '/diff': typeof DiffRoute
  '/hk4e': typeof Hk4eRoute
  '/hkrpg': typeof HkrpgRoute
  '/howto': typeof HowtoRoute
  '/hyg': typeof HygRoute
  '/kl': typeof KlRoute
  '/nap': typeof NapRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/abc': typeof AbcRoute
  '/bh3': typeof Bh3Route
  '/diff': typeof DiffRoute
  '/hk4e': typeof Hk4eRoute
  '/hkrpg': typeof HkrpgRoute
  '/howto': typeof HowtoRoute
  '/hyg': typeof HygRoute
  '/kl': typeof KlRoute
  '/nap': typeof NapRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/abc': typeof AbcRoute
  '/bh3': typeof Bh3Route
  '/diff': typeof DiffRoute
  '/hk4e': typeof Hk4eRoute
  '/hkrpg': typeof HkrpgRoute
  '/howto': typeof HowtoRoute
  '/hyg': typeof HygRoute
  '/kl': typeof KlRoute
  '/nap': typeof NapRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/abc'
    | '/bh3'
    | '/diff'
    | '/hk4e'
    | '/hkrpg'
    | '/howto'
    | '/hyg'
    | '/kl'
    | '/nap'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/abc'
    | '/bh3'
    | '/diff'
    | '/hk4e'
    | '/hkrpg'
    | '/howto'
    | '/hyg'
    | '/kl'
    | '/nap'
  id:
    | '__root__'
    | '/'
    | '/abc'
    | '/bh3'
    | '/diff'
    | '/hk4e'
    | '/hkrpg'
    | '/howto'
    | '/hyg'
    | '/kl'
    | '/nap'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AbcRoute: typeof AbcRoute
  Bh3Route: typeof Bh3Route
  DiffRoute: typeof DiffRoute
  Hk4eRoute: typeof Hk4eRoute
  HkrpgRoute: typeof HkrpgRoute
  HowtoRoute: typeof HowtoRoute
  HygRoute: typeof HygRoute
  KlRoute: typeof KlRoute
  NapRoute: typeof NapRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/nap': {
      id: '/nap'
      path: '/nap'
      fullPath: '/nap'
      preLoaderRoute: typeof NapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kl': {
      id: '/kl'
      path: '/kl'
      fullPath: '/kl'
      preLoaderRoute: typeof KlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hyg': {
      id: '/hyg'
      path: '/hyg'
      fullPath: '/hyg'
      preLoaderRoute: typeof HygRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/howto': {
      id: '/howto'
      path: '/howto'
      fullPath: '/howto'
      preLoaderRoute: typeof HowtoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hkrpg': {
      id: '/hkrpg'
      path: '/hkrpg'
      fullPath: '/hkrpg'
      preLoaderRoute: typeof HkrpgRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hk4e': {
      id: '/hk4e'
      path: '/hk4e'
      fullPath: '/hk4e'
      preLoaderRoute: typeof Hk4eRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/diff': {
      id: '/diff'
      path: '/diff'
      fullPath: '/diff'
      preLoaderRoute: typeof DiffRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bh3': {
      id: '/bh3'
      path: '/bh3'
      fullPath: '/bh3'
      preLoaderRoute: typeof Bh3RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/abc': {
      id: '/abc'
      path: '/abc'
      fullPath: '/abc'
      preLoaderRoute: typeof AbcRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AbcRoute: AbcRoute,
  Bh3Route: Bh3Route,
  DiffRoute: DiffRoute,
  Hk4eRoute: Hk4eRoute,
  HkrpgRoute: HkrpgRoute,
  HowtoRoute: HowtoRoute,
  HygRoute: HygRoute,
  KlRoute: KlRoute,
  NapRoute: NapRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
