// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

/**
 * @param {string} gamePath
 * @param {string} patchPath
 * @returns {$CancellablePromise<[boolean, string]>}
 */
export function ApplyDiffZip(gamePath, patchPath) {
    return $Call.ByID(1256177576, gamePath, patchPath);
}
